apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
type: Opaque
stringData:
  # A SecretKey DEVE ser idêntica à utilizada pela users-api para que os tokens JWT validem.
  MongoDbSettings__ConnectionString: "mongodb://mongodb:27017"
  JwtSettings__SecretKey: "FiapCloudGames_Dev_SecretKey_Com_Pelo_Menos_256_Bits_Para_HMAC_SHA256!"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
